### ISSUE TITLE
Navegacion entre paginas no funciona

### ISSUE THREAD

**Issue by guillebacigalupo** [guillebacigalupo/ganasafi#16]
Al navegar entre paginas desde el menu de https://ganasafi.herokuapp.com/ las paginas cargan en blanco.
Si se refresca la pagina o se accede con la URL desde el navegador directo, sí cargan bien.

En la pagina de FAQ no andan los desplegables de las preguntas que sí funcionaban.

**Comment by yosietserga** [comment]
[Commit db76bac](https://github.com/guillebacigalupo/ganasafi/commit/db76bac7d44f1849f42a79ff50ce9dd658729ed7)
