### ISSUE TITLE
Menu mobile no funciona

### ISSUE THREAD

**Issue by guillebacigalupo** [guillebacigalupo/ganasafi#17]
El menu mobile no funciona.

**Comment by guillebacigalupo** [comment]
<img width="313" alt="Screen Shot 2022-05-10 at 17 57 56" src="https://user-images.githubusercontent.com/42190145/167720645-0dd54905-7a96-4df1-8b2f-75a684d938cd.png">

**Comment by yosietserga** [comment]
[Commit db76bac](https://github.com/guillebacigalupo/ganasafi/commit/db76bac7d44f1849f42a79ff50ce9dd658729ed7)
